[versions]
kotlin = "2.2.21"
th2-plugin = "0.3.10"

[libraries]
th2-common = { group = "com.exactpro.th2", name = "common", version = "5.16.1-dev" }
th2-common-utils = { group = "com.exactpro.th2", name = "common-utils", version = "2.4.0-dev" }
th2-grpc-codec = { group = "com.exactpro.th2", name = "grpc-codec", version = "0.2.0-dev" }

kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging", version = "7.0.13" }
clikt = { group = "com.github.ajalt.clikt", name = "clikt", version = "5.0.3" }

auto-service = { group = "com.google.auto.service", name = "auto-service", version = "1.1.1" }
junit-bom = { group = "org.junit", name = "junit-bom", version = "5.14.1" }
strikt-core = { group = "io.strikt", name = "strikt-core", version = "0.34.1" } # jvm > 11 is required for versins after 0.34.1
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version = "6.1.0" }

[plugins]
th2-publish = { id = "com.exactpro.th2.gradle.publish", version.ref = "th2-plugin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }